### ISSUE TITLE
Health Check Endpoint

### ISSUE THREAD

**Issue by jakehow** [zipmark/gatekeeper#15]
This service needs a health check endpoint.  I think the only dependency is PG?

**Comment by mecampbellsoup** [comment]
Closing as this has [already been done](https://github.com/zipmark/gatekeeper/blob/08c9bb13f24a1740b4336dedac1b770681e43745/config/initializers/okcomputer.rb). No PG dependency; rather [it's AR.](https://github.com/sportngin/okcomputer/blob/master/lib/ok_computer/built_in_checks/active_record_check.rb#L15)
