### ISSUE TITLE
Cryptographic signing of JWT?

### ISSUE THREAD

**Issue by mecampbellsoup** [zipmark/gatekeeper#2]
https://github.com/jwt/ruby-jwt#algorithms-and-usage

@jakehow Are we going to cryptographically sign the JWTs we return to clients/vendors?

I noticed [this comment in `service`](https://github.com/zipmark/zipmark-service/blob/ab264d7d6e04dba32cff2fdd7c85a61ba8b56861/lib/zipmark/ext/sinatra/embed_base.rb#L55-L58) which seems to indicate we do not verify the signature of tokens currently...

That said, in our specs it [looks like we're at least using the application secret as the password/key](https://github.com/zipmark/zipmark-service/blob/ab264d7d6e04dba32cff2fdd7c85a61ba8b56861/spec/acceptance/v3/embed/manage-accounts/start_spec.rb#L43-L50) unless I'm reading that incorrectly.

**Comment by mecampbellsoup** [comment]
@jakehow actually, now that I've read that whole file, I see we use `JWT.decode` twice - [once without making sure it's signed to get the raw data, and again once we identify the vendor app and decode again using its secret](https://github.com/zipmark/zipmark-service/blob/ab264d7d6e04dba32cff2fdd7c85a61ba8b56861/spec/acceptance/v3/embed/manage-accounts/start_spec.rb#L43-L50).

I'm going to follow this same pattern, okay?

**Comment by jakehow** [comment]
@mecampbellsoup that works, the payload is not encrypted so you will get the vendor_app_id from the payload in order to confirm the signature.

**Comment by mecampbellsoup** [comment]
@jakehow just picking us discussion that started ove in `webhooks-api`:

https://github.com/zipmark/webhooks-api/pull/13#discussion_r56842644

So, each microservice will perform basic `JWT.decode` function on the token, without checking whether it's signed or not, since that latter task will be handled by `gatekeeper` correct? As in, the fact that the request made it thru `gatekeeper` and reached the `POST /deposits` (for example) endpoint in `service` indicates the token was valid & signed, right?

Sounds like we'll eventually have a gem that we bundle with each non-`gatekeeper` microservice that handles the `JWT.decode()[0][:vendor_application_id]` logic perhaps...?

**Comment by jakehow** [comment]
@mecampbellsoup no, the service will check that the JWT is signed and valid (there is no reason to have a network request for this).

If valid, it will check the auth service to ensure that it has not been revoked.  If it has not been revoked, it will make sure that the JWT has the correct claims (part of the payload) to access the service for that particular endpoint.

**Comment by mecampbellsoup** [comment]
@jakehow so each microservice will need access to the `vendor_applications` table, right?

> If valid, it will check the auth service to ensure that it has not been revoked. If it has not been revoked, it will make sure that the JWT has the correct claims (part of the payload) to access the service for that particular endpoint.

Well there's your network request... or are you just pointing out that 1 request is better than 2?

I'm going to open a separate issue to discuss how we structure and persist the claims data, and where.

**Comment by mecampbellsoup** [comment]
@jakehow should I work on a gem/middleware for this functionality: 

> ... the service will check that the JWT is signed and valid (there is no reason to have a network request for this).
>
> If valid, it will check the auth service to ensure that it has not been revoked. If it has not been revoked, it will make sure that the JWT has the correct claims (part of the payload) to access the service for that particular endpoint.

**Comment by mecampbellsoup** [comment]
@jakehow here's a pic of an example I've sketched out where a request comes into the `zipmark.com` domain via `POST /deposits`, while would be destined for the `service` API... I tried to outline each step of the auth process (assuming token auth). Please take a look and see my questions below.

![img_20160329_155131](https://cloud.githubusercontent.com/assets/2043821/14102750/ae4e5cc6-f5c6-11e5-9e04-0e834d2c9627.jpg)

### Questions:

* Will we need a PR to instruct, for example, `zipmark-service` to first check what kind of auth header is present (i.e. token vs. basic U/P) **first**, then either perform JWT auth or the existing basic auth? Is this the `service`-related work you alluded to before?
* I think it's best to wrap the functionality demonstrated in the above diagram/photo in a gem, and then use [a pattern like this](http://stackoverflow.com/a/20631324/2517033) to run it as middleware. The thing I'm not sure about is whether said gem would also handle the `GET /credentials/:token` bit to check if it's blacklisted or not. I think it *should*, since that's part of our token-based auth strategy (same "flow" as decoding the token and checking its scopes), however since it requires a network request to do this (or at least hitting a cache of some sort) it doesn't seem suitable for middleware. Thoughts on this?

**Comment by jakehow** [comment]
@mecampbellsoup the auth is going to continue being Basic Auth, however the secret will become a jwt for clients that have 'upgraded'

This means that the code will need to be invoked where the basic auth checking is currently happening in service.

Long term, and in other non-legacy services, a middleware is probably easiest.

**Comment by mecampbellsoup** [comment]
@jakehow closing this issue, as we've determined the strategy for [signing of newly-issued JWTs on `gatekeeper` using a master private key](https://github.com/zipmark/gatekeeper/blob/c32f4a4f8d26affb1c9a785dddbc0226b4443b6e/app/models/credential.rb#L38-L41), and having each respective microservice handle decoding them using a corresponding public key via the gem, `TokenAuthenticator`, which includes a middleware layer `TokenAuthenticator::Middleware` into the middleware stack. [Here's the gem logic where the JWT gets decoded and verified against `gatekeeper`'s blacklist.](https://github.com/zipmark/token_authenticator/blob/ae645abd18d75be1ae76159d8fcc4f1bf8e76fc6/lib/token_authenticator/token.rb#L13-L17).

I'll open issues in `token_authenticator` to ask a couple outstanding Q's I have.
