### ISSUE TITLE
Check Revocation List.

### ISSUE THREAD

**Issue by jakehow** [zipmark/gatekeeper#5]
This API needs and endpoint where other services can check a token against a revocation list.

**Comment by mecampbellsoup** [comment]
@jakehow shouldn't that just be part of the one [`POST /authentications`](https://github.com/zipmark/gatekeeper/blob/9528dc9ba7fc1208511917eb23391313fd99182f/config/routes.rb#L9) endpoint we have now? As in, part of ensuring a token is valid should be ensuring it's not been blacklisted...?

**Comment by jakehow** [comment]
@mecampbellsoup there should be no POST /authentications I dont think

there should be `GET /tokens/:token_id` which can return revocation status.
