### ISSUE TITLE
Credential Management

### ISSUE THREAD

**Issue by jakehow** [zipmark/gatekeeper#6]
Currently Application secrets are stored right on the vendor app model.

We need to make this a has_many relationship for security purposes.  This will enable integrated applications to rotate keys without incurring downtime, and also will allow them to use multiple keys for different services that are part of the same logical application.

* Create a new secret for an app
* List secrets attached to an app
* Delete (revoke) a secret which will add it to the revocation list for that app.

**Comment by mecampbellsoup** [comment]
@jakehow so this behavior, which relates to `VendorApplication#secret` (and will become `VendorApplication#secrets` via a `has_many` class macro), will obviously require changes to `app/models/vendor_application.rb`. 

Will those changes belong in a related `service` PR? Or in this API?

You want the 3 endpoints you specified above to be part of this API, right?

**Comment by jakehow** [comment]
@mecampbellsoup I think we should try to keep this as generic as possible.

We can model it as a `scope`, so we could just have a new table of credentials with id column, scope_id, scoped_by, and token.

This way we can use the same infrastructure for both API credential checking and user logins to the dashboard.

**Comment by jakehow** [comment]
@mecampbellsoup yes the three endpoints will need to be part of this API.  We will also need to make a PR and migration to use this service in the `service` repo.

**Comment by mecampbellsoup** [comment]
@jakehow...

> Will those changes [to the `VendorApplication` model] belong in a related service PR? Or in this API?

Just confirming the changes will be made in `service` where most/all of `VendorApplication` logic lives.

**Comment by mecampbellsoup** [comment]
> @mecampbellsoup I think we should try to keep this as generic as possible.

What is "this" in that sentence?

> We can model it as a scope, so we could just have a new table of credentials with id column, scope_id, scoped_by, and token.

What is "it" in that sentence?

**Comment by jakehow** [comment]
@mecampbellsoup this and it = the modeling in this service, ie there should be no reference or relationship to `VendorApplication`

**Comment by mecampbellsoup** [comment]
@jakehow in [this comment](https://github.com/zipmark/gatekeeper/issues/6#issue-142393134), have these endpoints:

> Create a new secret for an app
> List secrets attached to an app
> Delete (revoke) a secret which will add it to the revocation list for that app.

... become the CRUD endpoints which will interface with `token_credentials` table we've discussed?

**Comment by mecampbellsoup** [comment]
#9

**Comment by jakehow** [comment]
@mecampbellsoup correct
