### ISSUE TITLE
Require nonce parameter from clients to prevent replay attacks

### ISSUE THREAD

**Issue by mecampbellsoup** [zipmark/gatekeeper#7]
[Here](http://api.rubyonrails.org/classes/ActionController/HttpAuthentication/Digest.html#method-i-nonce) is a Rails implementation for reference.

[Replay attack](https://en.wikipedia.org/wiki/Replay_attack) definition.

[Helpful answer](http://crypto.stackexchange.com/a/1245) on SO.

**Comment by jakehow** [comment]
@mecampbellsoup dont think this is relevant to our use case
